resolver: ghc-8.5
allow-newer: true
flags:
  hashable:
    integer-gmp: false
extra-deps:
  - ansi-terminal-0.8.0.2
  - ansi-wl-pprint-0.6.8.2
  - base-compat-0.10.1
  - cereal-0.5.5.0
  - colour-2.3.4
  - happy-1.19.9
  - hashable-1.2.7.0
  - haskell-lexer-1.0.1
  - optparse-applicative-0.14.2.0
  - pretty-show-1.7
  - primitive-0.6.3.0
  - transformers-compat-0.6.1.6
  - unordered-containers-0.2.9.0
  - vector-0.12.0.1
packages:
  - asterius
  - binaryen
  - genapply
  - ghc-toolkit
  - ghc-toolkit-base
ghc-build: standard
setup-info:
  ghc:
    windows64:
      8.5.20180413:
        url: https://felis.sapiens.moe/ghc-8.5.20180413-x86_64-unknown-mingw32.tar.xz
        sha256: b4e511f04e75bed048dd5eeffa05e642284fa22d8c49d7306029c2951b4d135f
    linux64:
      8.5.20180413:
        url: https://felis.sapiens.moe/ghc-8.5.20180413-x86_64-unknown-linux.tar.xz
        sha256: 2cb3175b403b79a91c882ab8d506c79c49360418ad39d943b98f2a93aa3e300e
