version: 2

jobs:
  asterius:
    resource_class: xlarge
    docker:
      - image: ubuntu:bionic
    environment:
      DEBIAN_FRONTEND: noninteractive
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      MAKEFLAGS: -j9
    steps:
      - run:
          name: Install dependencies
          command: |
            apt update
            apt install -y \
              apt-transport-https \
              curl \
              software-properties-common
            curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
            add-apt-repository -y "deb https://deb.nodesource.com/node_10.x bionic main"
            apt update
            apt dist-upgrade -y
            apt install -y \
              autoconf \
              cmake \
              g++ \
              git \
              libedit-dev \
              libffi-dev \
              libgmp-dev \
              make \
              mkdocs \
              nodejs \
              xz-utils \
              zlib1g-dev
            mkdir -p ~/.local/bin
            curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      - checkout
      - run: git submodule update --init --recursive
      - run:
          name: Test Asterius & generate docs
          command: |
            export PATH=$PATH:~/.local/bin
            stack --no-terminal build --test --no-run-tests
            stack --no-terminal exec ahc-boot
            stack --no-terminal test asterius:fib
            cp -r asterius/test/fib /tmp/
            mkdocs build
            cp -r site /tmp/
      - persist_to_workspace:
          root: /tmp
          paths:
            - site
      - store_artifacts:
          path: /tmp/fib

  asterius-push-docs:
    docker:
      - image: ghcci/x86_64-linux:0.0.1
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: Ensure that GitHub is a known host (SSH)
          command: |
            if [ -z `ssh-keygen -F github.com` ]; then
              ssh-keyscan -H github.com >> ~/.ssh/known_hosts
            fi
      - run:
          name: Push documentation to gh-pages
          command: |
            cd /tmp/site
            touch .nojekyll
            git init
            git config user.email "cheng.shao@tweag.io"
            git config user.name "Shao Cheng"
            git checkout -b gh-pages
            git add --all
            git commit -q --message="Documentation of tweag/asterius@$CIRCLE_SHA1"
            git push git@github.com:tweag/asterius.git gh-pages --force

workflows:
  version: 2
  build:
    jobs:
      - asterius
      - asterius-push-docs:
          requires:
            - asterius
          filters:
            branches:
              only: master
