version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    environment:
      - GHC_VER: "8.5.20180413"
      - NIXPKGS_REV: fadcbfc2f593301c7dc22447ba1d7eed3549b1ac
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          cd .circleci
          docker login -u terrorjack -p $DOCKER_PASS
          docker build -t terrorjack/ghc-asterius:latest -t terrorjack/ghc-asterius:$GHC_VER --build-arg NIXPKGS_REV=$NIXPKGS_REV .
          docker push terrorjack/ghc-asterius:latest
          docker push terrorjack/ghc-asterius:$GHC_VER
